### ISSUE TITLE
Hanging or failing Braket tasks when evaluating many quantum circuits

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent-braket-plugin#41]
## Description

Executing the following braket task seems to hang indefinitely, or fail when `parallel=True` specified in the device

```python

@ct.electron(
    executor=braket_executor,
    deps_pip=braket_deps_pip
)
def do_quantum_svm(data, features, some_value=None):
    device_arn = os.environ["AMZN_BRAKET_DEVICE_ARN"]
    s3_bucket = os.environ["AMZN_BRAKET_OUT_S3_BUCKET"]
    s3_task_dir = os.environ["AMZN_BRAKET_TASK_RESULTS_S3_URI"].split(s3_bucket)[1]

    device = qml.device(
        "braket.aws.qubit",
        device_arn=device_arn,
        s3_destination_folder=(s3_bucket, s3_task_dir),
        wires=len(features),
        parallel=True
    )
    
    @qml.qnode(device)
    def kernel(x1, x2):
        qml.AngleEmbedding(x1, wires=features)
        qml.adjoint(qml.AngleEmbedding)(x2, wires=features)
        return qml.expval(qml.Projector(range(len(features)), features))

    quantum_kernel = lambda x1, x2: np.array([[kernel(i, j).numpy() for i in x1] for j in x2])
    model = svm.SVC(kernel=quantum_kernel)
    X_train, X_test, y_train, y_test = data
    X_train = X_train[:, features]
    X_test = X_test[:, features]

    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)

    return model, score
```

The following errors are logged when parallel execution is used:

```
INFO:backoff:Backing off get_quantum_task(...) for 0.3s (botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetQuantumTask operation: Quantum task fec9031b-91e8-42a9-b9de-d670bfb14045 not found)
```
```
Traceback (most recent call last):
  File "/opt/ml/code/exec.py", line 24, in <module>
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/covalent/executor/base.py", line 101, in wrapper_fn
    return TransportableObject(output)
  File "/usr/local/lib/python3.8/site-packages/covalent/_workflow/transport.py", line 47, in __init__
    self._object = base64.b64encode(cloudpickle.dumps(obj)).decode("utf-8")
  File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
Traceback (most recent call last): File "/opt/ml/code/exec.py", line 24, in <module> result = function(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/covalent/executor/base.py", line 101, in wrapper_fn return TransportableObject(output) File "/usr/local/lib/python3.8/site-packages/covalent/_workflow/transport.py", line 47, in __init__ self._object = base64.b64encode(cloudpickle.dumps(obj)).decode("utf-8") File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps cp.dump(obj) File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump return Pickler.dump(self, obj)
TypeError: cannot pickle 'SSLContext' object
```

**Comment by AlejandroEsquivel** [comment]
Was deemed to be internal latency of using Braket (about 4 seconds per circuit evaluation)
